lblod/mandataris-service

app.ts
routes/burgemeester-benoeming.ts
routes/intallatievergadering.ts

just moves the burgemeesterbenoeming to the router folder as a route to bring it inline with the rest of the service
the postman collection to approve and reject mayors should still work
[burgemeesterbenoemingen.json](https://github.com/lblod/mandataris-service/files/15332784/burgemeesterbenoemingen.json)

move burgemeesterbenoeming to route

---

controllers/mandataris-upload.ts
data-access/beleidsdomein.ts
data-access/mandataris.ts
data-access/persoon.ts
types.ts

Have the mandataris service create instances of mandataris on upload. It will not create a mandataris for the person if a mandataris was found in the same period. It create the link to fractions as well and sets the date for the membership appropriately.
Make sure to create the relevant fractions in the 2025-2030 governing period
Use the following file for the upload:
```csv
rrn,firstName,lastName,mandateName,startDateTime,endDateTime,fractieName,rangordeString,beleidsdomeinNames
00000000295,Johnny,New York,,,2030-05-13T11:32:12.038Z,Open VLD,,
00000000097,Jos,Janssens,Schepen,2024-01-01T12:00:12.038Z,2024-12-13T11:32:12.038Z,Open VLD,Eerste schepen,Cultuur|Sport en jeugd|Geitestoet
0000000O988,Georges,Janssens,Schepen,2024-01-01T12:00:12.038Z,2024-12-13T11:32:12.038Z,Open VLD,Tweede …
```

create mandataris instances

---

routes/burgemeester-benoeming.ts

The findBurgemeesterMandaat query seems broken in some instances. I got it to work by adding the missing xsd prefix to the query
We will need to deploy to dev to find out if it actually works as expected

Add xsd PREFIX to findBurgemeesterMandaat

---

routes/burgemeester-benoeming.ts

A developer who is wanting to use our endpoint burgemeester-benoeming is getting a statuscode 500 on his call. 
1. I ran the debugger and saw that the newMandatarisUri was a promise and so replace cannot be called. Added an await before it and the file uploaded as expected.

LMB-550 | Bug burgemeester benoeming | Cannot call replace on undefined

---

routes/burgemeester-benoeming.ts
util/mu.ts

Error warning in burgemeesterbenoemingen are a bit vague. Tell people what is wrong with the input and what valid input would look like.
When passing on values that we do not expect a clear error message is shown to the user.
Example of person not existing
Example for changed benoeming status
- https://github.com/lblod/mandataris-service/pull/13

LMB-559 | V2 improve error handling burgemeester benoeming

---

data-access/bestuursperiode.ts
data-access/burgemeester.ts
data-access/fractie.ts
data-access/linked-mandataris.ts
data-access/mandataris.ts
data-access/persoon.ts
routes/intallatievergadering.ts

moves some items that are under the ext prefix to the lmb prefix, which feels less brittle than ext
remove the database and bring it up from scratch. All features should still work.
Requires the app config to also be up to date with these changes
- https://github.com/lblod/app-lokaal-mandatenbeheer/pull/190

lmb prefix

---

controllers/mandataris.ts
routes/mandatarissen.ts

Expose the get decision for mandataris call as a route to be sued in the frontend
Use together with the frontend
- https://github.com/lblod/app-lokaal-mandatenbeheer/pull/221
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/327

lmb-698 |  add route to get the decision for the mandataris

---

controllers/mandataris.ts
cron/notification-for-bekrachtigde-mandataris.ts
data-access/mandataris.ts

We want to manipulate dates with the moment library
Check why the notification is send the day after set to effectief
1. Check the code that moment is used + date is formatted correctly (see query  in logs of mandataris service)
2. When bulk editing the publication status the effectiefAt triples are updated
**Previous date manipulation works**
**MomentJS format 
**Outgoing query for getting the mandatarissen looks good**
```sparql
.. prefixes
SELECT DISTINCT ?mandataris ?fName ?lName ?bestuursfunctieName ?graph
WHERE {
GRAPH ?graph {
?mandataris a mandaat:Mandataris ;
lmb:hasPublicationStatus <http://data.lblod.info/id/concept/MandatarisPublicationStatusCode/d3b12468-3720-4cb0-95b4-6aa2996ab188> ;
mandaat:isBestuurlijkeAliasVan ?person ;
org:holds / org:role ?bestuursfunctie .
?person …
```

lmb-960: date - 10 days to be done with moment js

---

routes/installatievergadering.ts

Only fracties, that were linked to the fake bestuursorganen, were copied when installatievergadering was finished and the mandatees of the ocmw got moved to the bestuurseenheid ocmw. This was no longer possible, since these fracties now have the link to the correct bestuursorganen (needed for GN).
Create some ocmw mandatees in the prepare iv, finish the iv and see if all are copied, both mandatees as fracties.

just copy all fracties of iv to ocmw

---

cron/notification-for-bekrachtigde-mandataris.ts
util/create-email.ts
util/create-notification.ts

Group bekrachtigingsmails per bestuurseenheid.
Also reduced the number of database queries for this logic. 
Few remarks:
There are some huge triples that need to be written, which might fail with the current tag of the database, best is to use the image `image: semtech/sparql-parser:0.0.12`.
You need to up the app with the profile=send-emails
Put the following in your docker-compose.override.yml in the app not sure you need it, but better safe than sorry:
```
deliver-email:
environment:
WELL_KNOWN_SERVICE: "test"
EMAIL_FROM_MANDATARIS_EFFECTIEF: "lokaalmandatenbeheer@vlaanderen.be" 
SEND_EMAIL_FOR_MANDATARIS_EFFECTIEF: true
```
Put the following in the override of the mandataris-service:
```
services:
mandataris:
restart: always
environment:
NOTIFICATION_CRON_PATTERN: "* * * * *" # Every …
```

send bekrachtigingsmails in bulk

---

app.ts
cron/fetch-bekrachtigingen.ts
util/uuid-for-uri.ts

This uses files produced by the harvesters to fetch decision data and processes them directly instead of using the delta consumer because the regular data harvested is too low in quality.
Run this on production data, afterwards, you should see bekrachtigde mandatarissen in multiple eenheden, e.g. zuienkerke: gemeenteraad (voorzitter & lid), schepenen, toegevoegde schepen, aangewezen burgemeester, leden en voorzitter van bscd 
Currently only deployed on harvester-2 so the other harvesters will give errors

fetch bekrachtigingen from files on harvester service and process them directly, disable old decision processing

---

controllers/linked-mandataris.ts
controllers/mandataris.ts
data-access/burgemeester.ts
data-access/mandataris-download.ts
data-access/mandataris.ts
util/date-manipulation.ts

Add a day to some queries when setting the end date for mandatarissen.
To test you need to trigger the flows that trigger the specific endpoints that update mandataris end dates, such as burgemeesterbenoeming, end active mandatees of a person ...
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/465
- https://github.com/lblod/app-lokaal-mandatenbeheer/pull/358

LMB-1288 make end dates of mandatarissen end of day end dates

---

data-access/orgaan.ts

when asking for an orgaan with mandatarissen in the future, it means we want the currently active mandatarissen. In that case use the current date instead of the last mandataris date (people put end dates in the future and end mandatarissen early, which results in a count that is too low sometimes)
View the count for Boechout, it should now be correct

fix count mandatarissen

---

controllers/mandataris.ts
cron/notification-for-bekrachtigde-mandataris.ts
data-access/burgemeester.ts
data-access/linked-mandataris.ts
data-access/mandataris.ts
data-access/orgaan.ts
routes/installatievergadering.ts
routes/mandatarissen.ts
routes/rangorde.ts
util/constants.ts
util/create-email.ts

When a new mandataris is created it needs to start in niet bekrachtigd publication status. Mandatarissen for IV should start in draft status. 
Renamed the constant, method names, etc..
TODO: but for the ticket where we fix the notifications/emails 
Togheter with the frontend.
1. create a linked mandataris
2. Generated mandatarissen in IV
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/500
- https://github.com/lblod/app-lokaal-mandatenbeheer/pull/386

Lmb 1407 | Soft removal draft publication status

---

data-access/mandataris.ts

End active mandatees was broken, this should fix it.
Try ending all mandatees linked to a person with the "beeindig" button.

LMB-1440 fix missing prefix

---

app.ts
cron/notification-for-bekrachtigde-mandataris.ts
data-access/mandataris.ts
docker-compose.debug.yml
package.json
routes/installatievergadering.ts
util/create-email.ts
util/create-notification.ts
util/http-error.ts

We want to change the logic for notifications. Before 10 days after effectief (niet-bekrachtigd publication status) a notification was send (this was disabled). We do want these notifications but when a mandataris is active for more than 10 days. (start date + 10 days  > today)
- Create a mandataris with start date 10 days past today, a notification should be create when the cron is executed
- [frontend](https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/515)
- [app](https://github.com/lblod/app-lokaal-mandatenbeheer/pull/398)

lmb-1428 | Notification for mandataris that is more than 10 days active

---

cron/notification-for-bekrachtigde-mandataris.ts
docker-compose.debug.yml
util/create-email.ts

don't mail for mayor, mail in plain text to avoid spam
have the cron job run (tweak the cron config and enable sending mails)
check the mails in the db, notice that they are now plain text instead of html
```
PREFIX nmo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#>
SELECT ?g ?s ?p ?o WHERE {
graph ?g {
?s a <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#Email>.
?s ?p ?o.
}
```
Notice that we're not mailing for mayors.

don't mail for mayor, mail in plain text to avoid spam

---

cron/notification-for-bekrachtigde-mandataris.ts

fix mails not being sent after op data reshuffle
run the mandataris service and set the cronjob to once a minute. Make sure to not actually send mails in your deliver email service

fix mails not being sent after op data reshuffle

---

controllers/linked-mandataris.ts

if the mandataris being created has a replacement, also mirror it to the ocmw
create a mandataris that is verhinderd with a replacement. see that it is mirrored to the ocmw

fix replacement not mirrored on create

---

routes/rangorde.ts

add lmb:linkToBesluit to preds to be ignored when copying during rangorde updates
update rangorde for mandatarissen who have a link to besluit. the link is no longer copied across and the state is still 'niet bekrachtigd'

fix rangorde copies link to besluit

---

controllers/fractie.ts
data-access/fractie.ts
data-access/mandataris.ts
docker-compose.debug.yml
routes/fractie.ts

We want fractions to be editable. But when a fraction changes a new one should be created.
1. The current fractie gets an `ext:endDate`
2. The replacement fractie gets a new relation to the old fraction with `dct:replaces`
3. All lidmaatschappen that had the old fraction connected have the new fraction 
4. All mandatarissen get a history item for this change with a message "CUSTOM"
- https://github.com/lblod/app-lokaal-mandatenbeheer/pull/460
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/603

LMB-1695 | Allow renaming fractions
