lblod/mandataris-service

app.ts, routes/intallatievergadering.ts
move fake ocmw mandataris instances to the real ocmw organs
add members to a fake ocmw organ, make sure these members have fractions
Use the frontend PR that makes the call in this service to move the mandatarisses of the ocmw organs to the correct ocmw organ in the ocwm graph
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/219
=> move fake ocmw mandataris instances to the real ocmw organs

.release-it.json, package-lock.json, package.json
Releasing newest version of service: **v0.0.3**
=> Version bump to v0.0.3

routes/burgemeester-benoeming.ts
Fix issue with base64 decoding.
You could try with Erik's curl, but it now gives unauthorized, plus it is a bug fix, so not sure if testing is worth it.
=> fix base64 decoding

controllers/mandatees-decisions.ts, data-access/mandatees-decisions.ts, routes/mandatees-decisions.ts, services/processing-queue.ts, types.ts
Now that we check the incoming triples from our delta we want to update the logic check the subjects that are incoming but do not have all values set yet. We will do this by keeping the mandataris subjects in a queue that we still have to check.
Logic should be updating inserting mandatarissen from the mandatees-decisions stream.
Everytime the endpoint is triggered and there are manually queued items it puts them in the current queue to be executed. As the queue is executing the queue executes the itens one by one so  I changed the parameter in the handle method only one subject instead of an array of subjects. 
- https://github.com/lblod/mandataris-service/pull/17
=> LMB-519 | Handle subject to check later

controllers/mandatees-decisions.ts, data-access/mandatees-decisions.ts, routes/mandatees-decisions.ts, services/processing-queue.ts
When the person is not found in database it needs to be created. Check the first and lastname on the mandataris subject itself. Persons are not being consumed by the BnB harvaster.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/180
=> LMB-520 | Create person from mandataris

controllers/mandatees-decisions.ts, data-access/mandatees-decisions.ts, data-access/persoon.ts, util/find-uuid-in-uri.ts
When the person doe snot exists in LMB but the mandataris has a link to a person create that person with the same URI in our database.
Test the query onn LMB for example:
```sparql
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX person: <http://www.w3.org/ns/person#>
PREFIX persoon: <http://data.vlaanderen.be/ns/persoon#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
INSERT DATA {
GRAPH <http://mu.semte.ch/graph/organizations/70b79f6678036bf05e970aa3885d1779f143d4eab63ecf339ea6263e7e76ad1d/LoketLB-mandaatGebruiker> {
<https://data.lblod.info/id/personen/198f938f5712141ed03e9dd27eb08c0e201fcfbc19e191ca2f77ae179ca8ac3d> a person:Person; 
mu:uuid "198f938f5712141ed03e9dd27eb08c0e201fcfbc19e191ca2f77ae179ca8ac3d";
persoon:gebruikteVoornaam "Joske";
foaf:familyName "De tester".
}
}
```
- …
=> LMB-520 | Create person from uri

app.ts, controllers/mandatees-decisions.ts, data-access/decision.ts, data-access/mandataris.ts, routes/delta.ts
Updating the endpoint as we also update the delta rule. From now on we will be getting artikel ?predicate ?mandataris in our changesets.  Check if the mandataris has a besluit and process the mandataris.
Look at the logs of the mandataris service. This can take a while...
- https://github.com/lblod/app-lokaal-mandatenbeheer/pull/174
=> LMB-524 | Only process mandatarissen with besluit

controllers/mandatees-decisions.ts, data-access/decision.ts, data-access/mandataris.ts, data-access/mandatees-decisions.ts, util/constants.ts
We want to automatically update the status of the mandataris when it is found in a besluit.
Run the query in your virtuoso endpoint for updating a status of a mandataris.
- https://github.com/lblod/app-lokaal-mandatenbeheer/pull/174 => **review this first**
=> LMB-523 | Set mandataris status to bekrachtigd when besluit is linked

docker-compose.debug.yml
Provide a detailed explanation of the changes you have made. Include the reasons behind these changes and any relevant context.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/180
=> feat: do not run the decisions sync wihtout a profile

controllers/persoon.ts, data-access/mandataris.ts, data-access/persoon.ts, routes/persoon.ts, util/constants.ts
An endpoint should be provided to "end" all active mandatarissen of a person
Call the endpoint through the button in the frontend.
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/300 **frontend**
=> LMB-336 | End all mandates for person

app.ts, controllers/fractie.ts, controllers/mandataris.ts, controllers/persoon.ts, data-access/bestuursperiode.ts, data-access/fractie.ts, data-access/mandataris.ts, data-access/persoon.ts, routes/fractie.ts, routes/persoon.ts, util/constants.ts
Dynamic fractie options are shown. Three scenario's:
1. create => show current or all
2. wijzig  => show fracties from the mandatarissen this person has in the bestuursperiode
3. correct => show all fracties from the bestuursperiode
Create, wijzig and correct a mandataris.
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/295
=> LMB-617 | Dynamic fractie options from lmb 640 | LATEST

app.ts, controllers/fractie.ts, controllers/mandataris.ts, controllers/persoon.ts, data-access/bestuursperiode.ts, data-access/fractie.ts, data-access/mandataris.ts, data-access/persoon.ts, routes/fractie.ts, routes/persoon.ts, util/constants.ts
Getting the data needed for our frontend.
1. Use it togheter with the frontend
2. look at the code
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/290
- https://github.com/lblod/app-lokaal-mandatenbeheer/pull/183
=> LMB-640 | Has many relation to fractie for person

controllers/mandataris.ts, data-access/mandataris.ts, routes/mandatarissen.ts, util/constants.ts, util/sparql-escape.ts
We want to copy over the predicates of a mandataris that are not in our resouce domain or ember model. With this endpoint we filter out all these predicates and add it to the new mandataris.
Through the frontend change the state of a mandataris.
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/304
=> LMB-212 | Copy mandataris endpoint

app.ts, cron/notification-for-bekrachtigde-mandataris.ts, docker-compose.debug.yml, package-lock.json, package.json, types.ts, util/constants.ts, util/create-notification.ts
Create a notification when a mandataris has effectief status but is not bekrachtigd yet.
Run the APP PR and than run the mandataris service. you should see some system notifications.
- https://github.com/lblod/app-lokaal-mandatenbeheer/pull/217
- Karels PR for system notifications per bestuurseenheid https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/326
=> LMB 339 |  cron to check effectief to bekrachtigd

cron/notification-for-bekrachtigde-mandataris.ts, data-access/bestuurseenheid.ts, docker-compose.debug.yml, util/create-email.ts
An email must be send to the bestuurseeneheid contact when there is a mandataris with publication status effectief for 10 or more days.
Run the deliver mail service togheter with this PR and see if eny mails are created in the mandataris logs. Than look at the app deliver-email service logs to see if the mail is created and you can see a preview url.
- https://github.com/lblod/app-lokaal-mandatenbeheer/pull/218
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/328
=> Lmb 557 |  email on effectief older than 10 days

routes/installatievergadering.ts
fractietype predicate was wrong.
=> fix fractietype predicate

routes/installatievergadering.ts
Update state of IV OCMW when we copy over the mandatarissen from the municipality graph to the OCMW graph.
If needed this can also be done as a dedicated call.
First run the migration in the linked PR. Then check in an OCMW if the current period is locked (for adding mandatees etc). Then go to the corresponding municipality and finish the IV. Now, the current period in the OCMW should no longer be locked.
- https://github.com/lblod/app-lokaal-mandatenbeheer/pull/255
=> update state iv OCMW when moving mandatarissen

routes/installatievergadering.ts
fix broken memberof link for fractions: a link is created to the fake bestuursorganen we create to make the iv prep possible. We should change it to the real organen from the ocmw.
Have this cron run for 10 minutes, then check if the link is updated to the true bestuursorganen of the ocmw
=> fix broken memberof link for fractions

app.ts, package-lock.json, package.json, routes/verkiezingsresultaten.ts
allow downloading election results
=> allow downloading election results

data-access/delete.ts, routes/fractie.ts, routes/mandatarissen.ts
allow deleting fracties with tombstone
see linked pr
- https://github.com/lblod/app-lokaal-mandatenbeheer/pull/272
=> allow deleting fracties with tombstone

data-access/burgemeester.ts, data-access/linked-mandataris.ts, data-access/mandaat.ts, routes/installatievergadering.ts
fix all persons were attempted to be moved, improve selection of important graphs, improve efficiency
complete the iv for a municipality. see that everything for this municipality is moved (but not for others)
- requires: https://github.com/lblod/app-lokaal-mandatenbeheer/pull/283
=> fix all persons were attempted to be moved, improve selection of important graphs, improve efficiency

controllers/mandataris.ts, routes/mandatarissen.ts
Remove endpoint that is no longer useful.
See linked PR.
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/429
=> LMB-1078 remove useless endpoint

cron/notification-for-bekrachtigde-mandataris.ts, docker-compose.debug.yml, util/create-email.ts
Update the content of the email send when a mandataris is publication status effectief for more than 10 days without a besluit.
Set `SEND_EMAIL_FOR_MANDATARIS_EFFECTIEF` to true in debug compose file of mandataris service
And lookat the logs of lmb app `deliver-email`
=> Lmb 1004 : update email content

data-access/delete.ts, data-access/fractie.ts, routes/installatievergadering.ts
tombstones did not receive a modified date
delete a mandataris, fractie etc and see that a modified date is created on its tombstone
=> fix no modified for tombstones

routes/installatievergadering.ts
when completing the iv, mark mandataris instances as effective, for both ocmw and regular organs
complete iv, check mandataris by uri for gemeente and ocmw, see that all triples in owned by graphs have the new publication status
=> mark mandatarisses effective after iv

cron/notification-for-bekrachtigde-mandataris.ts, data-access/mandataris.ts, docker-compose.debug.yml, util/constants.ts
Only mandatarissen that are effectief longer than 10 days AND do not have a notification yet are set. Email is not optional when getting it from the bestuurseenheid
Run it with an email and boolean set to true
=> lmb-1123: fix email get must have email

routes/installatievergadering.ts
don't make new fractie uris in ocmw
go to a bestuurseenheid that hasn't completed their iv yet, e.g. herent and complete it. you should still see fractions in the ocmw, they have the same uri as the ones in the gemeente.
=> don't make new fractie uris in ocmw

cron/notification-for-bekrachtigde-mandataris.ts
Add early return in the notifications / mails for bekrachtigde mandatarissen without besluit.
=> Small improvement bulk emails

docker-compose.debug.yml, routes/installatievergadering.ts
ending iv failed in some cases on generating memberships. this is a more efficient version
end iv for oud-heverlee
=> more efficient end iv

cron/notification-for-bekrachtigde-mandataris.ts, data-access/file.ts, data-access/form-queries.ts, data-access/fractie.ts, package-lock.json, package.json, routes/installatievergadering.ts, tsconfig.json, util/create-notification.ts
We want every user input value in the query to be escaped to prevent sparql injection.
User inputted values are escaped
- [V1](https://github.com/lblod/mandataris-service/pull/84) **DEPRECATED**
- https://github.com/lblod/form-content-service/pull/70
- https://github.com/lblod/app-lokaal-mandatenbeheer/pull/359
=> lmb-1055: escape all user input values **V2**

data-access/mandataris-download.ts
It seems without a str call virtuoso isn't comparing these dates properly.
Download prod data and download the mandatarissen of commissie A in hemiksem
=> fix download mandatarissen for custom organs

app.ts, routes/rangorde.ts
Add endpoint to update rangordes.
See frontend
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/472
=> LMB-1164 add endpoint to update rangordes

cron/fetch-bekrachtigingen.ts
this fixes bekrachtigingen that were being created for previous periods and for mandatarissen starting after the iv
starting from old data (< 2025-02-11) hove should not receive bekrachtigingen if you sync with the harvesters and the new mandatarissen in houthalen-helchteren should be on effectief
=> fix too many bekrachtigingen

controllers/mandataris.ts, data-access/mandataris.ts, data-access/persoon.ts, routes/persoon.ts
Extend endpoints for ending active mandatarissen with date and bestuursperiode.
See frontend.
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/503
=> Ben/lmb 1311 Request date parameter when ending mandates

data-access/burgemeester.ts, data-access/mandataris.ts
Some weird uris where used for new mandatarissen in burgemeester flow.
Check if the uri is now better.
=> fix prefix new mandataris uris

app.ts, controllers/mandataris.ts, data-access/mandataris.ts, docker-compose.debug.yml, routes/delta-decisions.ts, routes/delta-politiezones.ts, routes/delta-router.ts, routes/mandatarissen.ts
allow shared groups of police zone groups, powered by deltas.
see linked pr
https://github.com/lblod/app-lokaal-mandatenbeheer/pull/367
=> allow shared management of police zone groups powered by deltas

cron/notification-for-bekrachtigde-mandataris.ts, data-access/burgemeester.ts, data-access/form-queries.ts, data-access/linked-mandataris.ts, data-access/mandataris.ts, data-access/persoon.ts, routes/delta-politiezones.ts, routes/installatievergadering.ts, util/create-notification.ts
rewrite sudo queries where necessary to accomodate change of mandaat, org and eenheid moving to public as owned by OP
test app behaviour related to:
- notifications
- installatievergadering
- rangorde
- linked mandatarissen
- mirroring of police-council mandatarissen
=> rewrite sudo queries where necessary to accomodate change of mandaat, org and eenheid moving to public as owned by OP
